name: yo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  shimmer: ^1.0.1
  firebase_analytics: ^5.0.14
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_database: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "icons/App.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
      # Presentación
      - assets/presentacion/FONDO.png
      - assets/presentacion/App.jpg
      # EjesTransversales
      - icons/EjesTrans/PorResp.jpeg
      - icons/EjesTrans/AntesDeElegir.jpeg
      - icons/EjesTrans/VidaSalu.jpeg
      - icons/EjesTrans/ProyectoVida.jpeg
      - icons/EjesTrans/1.jpeg
      - icons/EjesTrans/2.jpeg
      - icons/EjesTrans/3.jpeg
      - icons/EjesTrans/4.jpeg
      # Por respeto a mi y a los demas
      - icons/PorRespA/Acoso.jpg
      - icons/PorRespA/Bulling.jpg
      - icons/PorRespA/Violencia.jpg
      # Tengo Una Vida Saludable
      - icons/VidaSalu/Adicciones.jpg
      - icons/VidaSalu/TiempoLibre.jpg
      - icons/VidaSalu/HabitosAlimenticios.jpg
      - icons/VidaSalu/HabitosDeEjercicio.jpg
      # Antes de Elegir me Informo
      - icons/AntesDeEleg/Sexualidad.jpg
      - icons/AntesDeEleg/IdentidadDeGenero.jpg
      # Construyo Un Proyecto de Vida
      - icons/ProyectoDeVida/Aspiraciones.jpg
      - icons/ProyectoDeVida/Intereses.jpg
      - icons/ProyectoDeVida/PreferenciasDeEstudio.jpg
      # Slider Pantalla 1
      - assets/SliderPantalla1/image1.jpg
      - assets/SliderPantalla1/image3.jpg
      - assets/SliderPantalla1/image4.jpg
      - assets/SliderPantalla1/image5.jpg
      - assets/SliderPantalla1/image6.jpg
      - assets/SliderPantalla1/image7.jpg
      # "Información" Por Respeto A mi Y  A lOS demas
      - icons/PorRespA/Subtemas/Acoso2.jpg
      - icons/PorRespA/Subtemas/Bulling2.jpg
      - icons/PorRespA/Subtemas/Violencia2.jpg
      # "Información" Vida Saludable
      - icons/VidaSalu/Subtemas/Adicciones2.jpg
      - icons/VidaSalu/Subtemas/HabitosAlimenticios2.jpg
      - icons/VidaSalu/Subtemas/HabitosDeEjercicio2.jpg
      - icons/VidaSalu/Subtemas/TiempoLibre2.jpg
      # "Información" Antes De Elegir Me Informo
      - icons/AntesDeEleg/Subtemas/Sexualidad2.jpg
      - icons/AntesDeEleg/Subtemas/IdentidadDeGenero2.jpg
      # "Información" Construyo Un Proyecto De Vida
      - icons/ProyectoDeVida/Subtemas/Aspiraciones2.jpg
      - icons/ProyectoDeVida/Subtemas/Intereses2.jpg
      - icons/ProyectoDeVida/Subtemas/PreferenciasDeEstudio2.jpg
      # "Informacion" Habitos fisicos
      - assets/habitofisico/una.jpg
      - assets/habitofisico/dos.jpeg
      - assets/habitofisico/tres.jpeg
      - assets/habitofisico/cuatro.jpeg
      - assets/habitofisico/cinco.jpeg
      - assets/habitofisico/seis.jpeg
      - assets/habitofisico/siete.jpeg
      - assets/habitofisico/ocho.jpeg
      - assets/habitofisico/nueve.jpeg
      # "Informacion" Habitos alimenticios
      - assets/habitoalimenticio/una.jpeg
      - assets/habitoalimenticio/dos.jpeg
      - assets/habitoalimenticio/tres.jpeg
      - assets/habitoalimenticio/cuatro.jpeg
      - assets/habitoalimenticio/cinco.jpeg
      - assets/habitoalimenticio/seis.jpeg
      - assets/habitoalimenticio/siete.jpeg
      - assets/habitoalimenticio/ocho.jpeg
      - assets/habitoalimenticio/nueve.jpeg
      - assets/habitoalimenticio/diez.jpeg
      - assets/habitoalimenticio/tema1.png
      - assets/habitoalimenticio/tema1a.png
      - assets/habitoalimenticio/tema1b.png
      - assets/habitoalimenticio/tema1c.png
      - assets/habitoalimenticio/tema1d.png
      # "Informacion" Sexualidad
      - assets/sexualidad/img1.png
      - assets/sexualidad/img2.png
      - assets/sexualidad/img3.png
      - assets/sexualidad/img4.png
      - assets/sexualidad/img5.png
      - assets/sexualidad/img6.png
      - assets/sexualidad/img7.png
      - assets/sexualidad/img8.png
      - assets/sexualidad/img9.png
      - assets/sexualidad/img10.png
      - assets/sexualidad/img11.png
      - assets/sexualidad/img12.png
      - assets/sexualidad/img13.png
      - assets/sexualidad/img14.png
      # "Informacion" Tiempolibre
      - assets/tiempolibre/img1.png
      - assets/tiempolibre/img2.png
      - assets/tiempolibre/img3.png
      - assets/tiempolibre/img4.png
      - assets/tiempolibre/img5.png
      - assets/tiempolibre/img6.png
      # "Informacio" Bullying
      - assets/bullying/img1a.png
      - assets/bullying/img1b.png
      - assets/bullying/img1.jpg
      - assets/bullying/img2.jpg
      - assets/bullying/img3.jpg
      - assets/bullying/img4.jpg
      - assets/bullying/img5.jpg
      - assets/bullying/img6.jpg
      # "Informacion" Acoso
      - assets/acoso/img1.png
      - assets/acoso/img2.png
      - assets/acoso/img3.png
      - assets/acoso/img4.png
      # Informacion" Preferencias Estudio
      - assets/preferenciasestudio/img1.png
      - assets/preferenciasestudio/img2.png
      - assets/preferenciasestudio/img3.png
      - assets/preferenciasestudio/img4.png
      - assets/preferenciasestudio/img5.png
      - assets/preferenciasestudio/img6.png
      - assets/preferenciasestudio/img7.png
      - assets/preferenciasestudio/img8.png
      - assets/preferenciasestudio/img9.png
      - assets/preferenciasestudio/img10.png
      - assets/preferenciasestudio/img11.png
      - assets/preferenciasestudio/img12.png
      - assets/preferenciasestudio/img13.png
      # "Informacion" Intereses
      - assets/intereses/img1.png
      # "Informacion" Aspiraciones
      - assets/aspiraciones/img1.png
      - assets/aspiraciones/img2.png
      - assets/aspiraciones/img3.png
      - assets/aspiraciones/img4.png
      - assets/aspiraciones/img5.png
      - assets/aspiraciones/img6.png
      - assets/aspiraciones/img7.png
      # "Informacion" Identidad Genero
      - assets/identidadgenero/img1.png
      - assets/identidadgenero/img2.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
